services:
  iam:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    restart: always
    ports:
      - '3002:3002'
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      NODE_ENV: development

networks:
  app-network:
    driver: bridge
